---
title: "R Notebook"
output: html_notebook
---

 CARREGANDO OS DADOS DAS ELEIÇÕES
```{r}
# Notebook de dados descaracterizados de uma eleição

eleicao = read.csv('Eleicao.csv', sep = ';', header = T)

```

VISUALIZANDO OS DADOS

-> RELAÇÃO ENTRE DESPESAS E A SITUAÇÃO DO CANDIDATO

```{r}

plot(eleicao$DESPESAS, eleicao$SITUACAO)

summary(eleicao)

```

CORRELAÇÃO

```{r}

cor(eleicao$DESPESAS, eleicao$SITUACAO)

```
MODELO DE REGRESSÃO LOGISTICA

```{r}

modelo = glm(SITUACAO ~ DESPESAS, data = eleicao, family = "binomial")
summary(modelo)

```

```{r}

plot(eleicao$DESPESAS, eleicao$SITUACAO, col='red', pch=20)
points(eleicao$DESPESAS, modelo$fitted, pch=4)


```
CRIANDO O MODELO DE PREVISAO LOGISTICA
```{r}
prever = predict(modelo, newdata = eleicao, type = "response")
prever <- prever >= 0.5
prever
```

```{r}
confusao = table(prever, eleicao$SITUACAO)
confusao
taxaacerto = (confusao[1] + confusao[4])/sum(confusao)
taxaacerto


```

```{r}
preview = read.csv("NovosCandidatos.csv", sep = ";", header = T)
preview
```


```{r}
preview$RESULT = predict(modelo, newdata = preview, type = "response")
preview$RESULT >= 0.5
```

